/*
 * These are skill_lookup return values for common skills and spells.
 */
GSN(gsn_armor_use)
GSN(gsn_assassinate)
GSN(gsn_backstab)

GSN(gsn_dodge)
GSN(gsn_envenom)
GSN(gsn_hide)
GSN(gsn_hunt)
GSN(gsn_peek)
GSN(gsn_pick_lock)
GSN(gsn_sap)
GSN(gsn_sneak)
GSN(gsn_steal)
GSN(gsn_plant)

GSN(gsn_awareness)
GSN(gsn_alertness)
GSN(gsn_observation)
GSN(gsn_overwhelm)
GSN(gsn_bind)
GSN(gsn_escape)

GSN(gsn_disarm)
GSN(gsn_enhanced_damage)
GSN(gsn_critical)
GSN(gsn_kick)
GSN(gsn_parry)
GSN(gsn_rescue)
GSN(gsn_second_attack)
GSN(gsn_third_attack)
GSN(gsn_fourth_attack)
GSN(gsn_fifth_attack)

GSN(gsn_blindness)
GSN(gsn_bond)
GSN(gsn_charm_person)
GSN(gsn_curse)
GSN(gsn_invis)
GSN(gsn_mirror_of_mists)
GSN(gsn_mass_invis)
GSN(gsn_mask_channelling)
GSN(gsn_plague)
GSN(gsn_poison)
GSN(gsn_suffocate)
GSN(gsn_sleep)
GSN(gsn_fly)
GSN(gsn_sanctuary)

/* weapon gsns */
GSN(gsn_arrow)
GSN(gsn_axe)
GSN(gsn_bow)
GSN(gsn_dagger)
GSN(gsn_flail)
GSN(gsn_mace)
GSN(gsn_lance)
GSN(gsn_polearm)
GSN(gsn_spear)
GSN(gsn_sword)
GSN(gsn_whip)
GSN(gsn_staff)

GSN(gsn_sharpen)
GSN(gsn_shield_block) 
GSN(gsn_bash)
GSN(gsn_berserk)
GSN(gsn_dirt)
GSN(gsn_hand_to_hand)
GSN(gsn_trip)
GSN(gsn_herbs)
GSN(gsn_dual_wield)
GSN(gsn_camouflage)
GSN(gsn_riding)
GSN(gsn_charge)
GSN(gsn_bash_door)
GSN(gsn_fade)
GSN(gsn_push)
GSN(gsn_throw)
GSN(gsn_butcher)
GSN(gsn_circle) 
GSN(gsn_blademaster)
GSN(gsn_trollocwarfare)
GSN(gsn_speardancer)
GSN(gsn_duelling)
GSN(gsn_axemaster)
GSN(gsn_flailmaster)
GSN(gsn_whipmaster)
GSN(gsn_staffmaster)
GSN(gsn_martialarts)

GSN(gsn_sharpen)
GSN(gsn_fast_healing)
GSN(gsn_haggle)
GSN(gsn_link)
GSN(gsn_lore)
GSN(gsn_meditation)
GSN(gsn_guard)
GSN(gsn_block)
 
GSN(gsn_scrolls)
GSN(gsn_staves)
GSN(gsn_wands)
GSN(gsn_recall)

/* Channeling related gsns */
GSN(gsn_seize)
GSN(gsn_embrace)
GSN(gsn_tying)
GSN(gsn_conceal)

/* Weaves */
GSN(gsn_bof)
GSN(gsn_wof)
GSN(gsn_woa)
GSN(gsn_disguise)
GSN(gsn_create_angreal)
GSN(gsn_keep)

GSN(gsn_dream)
GSN(gsn_invert)

/* Ogier */
GSN(gsn_singwood)

/* Mining and Gemcasting */
GSN(gsn_mine)
GSN(gsn_smelt)
GSN(gsn_gemmine)
GSN(gsn_gemcut)
GSN(gsn_armorcraft)
GSN(gsn_jewelcraft)

/* New Granted Skills */
GSN(gsn_ironwill)
GSN(gsn_whirlwind)
GSN(gsn_concussionblow)
GSN(gsn_flamevoid)

