/***************************************************************************
 *  Original Diku Mud copyright (C) 1990, 1991 by Sebastian Hammer,      *
 *  Michael Seifert, Hans Henrik St{rfeldt, Tom Madsen, and Katja Nyboe.   *
 *                                              *
 *  Merc Diku Mud improvments copyright (C) 1992, 1993 by Michael        *
 *  Chastain, Michael Quan, and Mitchell Tse.                       *
 *                                              *
 *  In order to use any part of this Merc Diku Mud, you must comply with   *
 *  both the original Diku license in 'license.doc' as well the Merc     *
 *  license in 'license.txt'.  In particular, you may not remove either of *
 *  these copyright notices.                              *
 *                                              *
 *  Much time and thought has gone into this software and you are        *
 *  benefitting.  We hope that you share your changes too.  What goes    *
 *  around, comes around.                                 *
 ***************************************************************************/
 
/***************************************************************************
*    ROM 2.4 is copyright 1993-1998 Russ Taylor                *
*    ROM has been brought to you by the ROM consortium         *
*        Russ Taylor (rtaylor@hypercube.org)                   *
*        Gabrielle Taylor (gtaylor@hypercube.org)              *
*        Brian Moore (zump@rom.org)                            *
*    By using this code, you have agreed to follow the terms of the      *
*    ROM license, in the file Rom24/doc/rom.license                 *
***************************************************************************/


/*
 * Spell functions.
 * Defined in magic.c.
 */
SPELL(   spell_null           )
SPELL(   spell_acid_blast     )
SPELL(   spell_air_dome       )
SPELL(   spell_armor          )
SPELL(   spell_autokiller     )
SPELL(   spell_balefire       )
SPELL(   spell_baroffire      )
SPELL(   spell_blastofair     )
SPELL(   spell_bless          )
SPELL(   spell_blizzard       )
SPELL(   spell_bond           )
SPELL(   spell_blade          )
SPELL(   spell_blindness          )
SPELL(   spell_burning_hands )
SPELL(   spell_call_lightning     )
SPELL(   spell_calm      )
SPELL(   spell_cancellation   )
SPELL(   spell_cause_critical     )
SPELL(   spell_cause_light   )
SPELL(   spell_cause_serious )
SPELL(   spell_change_sex    )
SPELL(   spell_chain_lightning   )
SPELL(   spell_charm_person  )
SPELL(   spell_chill_touch   )
SPELL(   spell_colour_spray  )
SPELL(   spell_continual_light    )
SPELL(   spell_control_weather    )
SPELL(   spell_create_angreal )
SPELL(   spell_create_flame  )
SPELL(   spell_create_food   )
SPELL(   spell_create_rain   )
SPELL(   spell_create_rose   )
SPELL(   spell_create_spring )
SPELL(   spell_create_water  )
SPELL(   spell_cure_blindness)
SPELL(   spell_cure_critical )
SPELL(   spell_cure_disease  )
SPELL(   spell_cure_light    )
SPELL(   spell_cure_poison   )
SPELL(   spell_cure_serious  )
SPELL(   spell_delve         )
SPELL(   spell_demonfire     )
SPELL(   spell_detect_hidden )
SPELL(   spell_detect_invis  )
SPELL(   spell_detect_poison )
SPELL(   spell_disguise      )
SPELL(   spell_dispel_evil   )
SPELL(   spell_dispel_good   )
SPELL(   spell_dispel_magic  )
SPELL(   spell_dreamgate     )
SPELL(   spell_dreamward     )
SPELL(   spell_earthquake    )
SPELL(   spell_eavesdrop      )
SPELL(   spell_eavesdropward )
SPELL(   spell_enchant_armor )
SPELL(   spell_enchant_weapon     )
SPELL(   spell_energy_drain  )
SPELL(   spell_faerie_fire   )
SPELL(   spell_faerie_fog    )
SPELL(   spell_farsight      )
SPELL(   spell_fireball      )
SPELL(   spell_fireproof          )
SPELL(   spell_flamestrike   )
SPELL(   spell_floating_disc )
SPELL(   spell_fly      )
SPELL(   spell_flyingrocks )
SPELL(   spell_frenzy      )
SPELL(   spell_gag          )
SPELL(   spell_gate          )
SPELL(   spell_giant_size )
SPELL(   spell_giant_strength     )
SPELL(   spell_grow_berries )
SPELL(   spell_gust_of_wind  )
SPELL(   spell_harm          )
SPELL(   spell_haste       )
SPELL(   spell_heal          )
SPELL(   spell_minor_heal    )
SPELL(   spell_mirror_of_mists )
SPELL(   spell_major_heal    )
SPELL(   spell_heal_still    )
SPELL(   spell_heat_metal    )
SPELL(   spell_holy_word        )
SPELL(   spell_hurricane     )
SPELL(   spell_identify      )
SPELL(   spell_inferno )
SPELL(   spell_infravision   )
SPELL(   spell_invis         )
SPELL(   spell_keep          )
SPELL(   spell_know_alignment     )
SPELL(   spell_light_ward )
SPELL(   spell_lightningbolt )
SPELL(   spell_lightning_bolt     )
SPELL(   spell_locate_object )
SPELL(   spell_magic_missile )
SPELL(   spell_mass_healing     )
SPELL(   spell_mass_invis    )
SPELL(   spell_mind_flay     )
SPELL(   spell_nexus         )
SPELL(   spell_pass_door          )
SPELL(   spell_pinch         )
SPELL(   spell_plague        )
SPELL(   spell_poison        )
SPELL(   spell_portal             )
SPELL(   spell_ray_of_truth  )
SPELL(   spell_recharge      )
SPELL(   spell_refresh       )
SPELL(   spell_remove_curse  )
SPELL(   spell_rollingring      )
SPELL(   spell_sanctuary          )
SPELL(   spell_shadowspawn_ward )
SPELL(   spell_shocking_grasp     )
SPELL(   spell_shielding     )
SPELL(   spell_shimmer       )
SPELL(   spell_skimming      )
SPELL(   spell_sleep         )
SPELL(   spell_slice         )
SPELL(   spell_slow          )
SPELL(   spell_spinning_earthfire  )
SPELL(   spell_still         )
SPELL(   spell_stream_of_water )
SPELL(   spell_stone_skin    )
SPELL(   spell_suffocate     )
SPELL(   spell_summon        )
SPELL(   spell_teleport      )
SPELL(   spell_thunderclap   )
SPELL(   spell_token         )
SPELL(   spell_ventriloquate )
SPELL(   spell_wall_of_air   )
SPELL(   spell_wall_of_fire  )
SPELL(   spell_waterball     )
SPELL(   spell_weaken        )
SPELL(   spell_word_of_recall)
SPELL(   spell_wrap          )
SPELL(   spell_acid_breath   )
SPELL(   spell_fire_breath   )
SPELL(   spell_frost_breath  )
SPELL(   spell_gas_breath    )
SPELL(   spell_lightning_breath   )
SPELL(   spell_general_purpose    )
SPELL(   spell_high_explosive     )
